apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: site
          image: shaytu2/weather-eks:31
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - port: 9090 # Deployment port/service
      targetPort: 9090 # Pod port in Deployment/service
      nodePort: 30002 # Node port that will connect to the Deployment
  # template:
  #   spec:
  #     containers:
  #       - image: nickgofman/weather:color
